config/routes.rb
Rails.application.routes.draw do

  namespace :api , :defaults => { :format => 'json' } do
    scope :module => :v1 do
      scope :module => :agency_app do
        post 'create_agency', :to => 'agencies#create', :as => :create_agency
        post 'filter_agencies', :to => 'agencies#filter_agencies', :as => :filter_agencies
      end
    end
  end
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  acts_as_taggable
end

app/controllers/api/v1/agency_app/agencies_controller.rb
class Api::V1::AgencyApp::AgenciesController < Api::V1::BaseController

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)
    @agency.tag_list = params[:tags]
    @agency.save
  end

  def filter_agencies
    if (params[:tags].present? && params[:name].present?)
      @agencies = Agency.tagged_with(params[:tags], :any => true,:wild => true).where("name ILIKE ? ","%#{params[:name]}%").order(:grade)
    elsif params[:tags].present?
      @agencies = Agency.tagged_with(params[:tags], :any => true,:wild => true).order(:grade)
    elsif params[:name].present?
      @agencies = Agency.where("name ILIKE ? ","%#{params[:name]}%").order(:grade)
    else
      @agencies =  Agency.order(:grade)
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.


  # Never trust parameters from the scary internet, only allow the white list through.
  def agency_params
    params.require(:agency).permit(:name,:description,:tags,:grade)
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  skip_before_filter  :verify_authenticity_token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/api/v1/agency_app/agencies_helper.rb
module Api::V1::AgencyApp::AgenciesHelper
end

app/helpers/api/v1/base_helper.rb
module Api::V1::BaseHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agencies/_form.html.erb
<%= form_for(@agency) do |f| %>
  <% if @agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
      <% @agency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agencies/edit.html.erb
<h1>Editing Agency</h1>

<%= render 'form' %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Agencies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agencies.each do |agency| %>
      <tr>
        <td><%= link_to 'Show', agency %></td>
        <td><%= link_to 'Edit', edit_agency_path(agency) %></td>
        <td><%= link_to 'Destroy', agency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agency', new_agency_path %>

app/views/agencies/new.html.erb
<h1>New Agency</h1>

<%= render 'form' %>

<%= link_to 'Back', agencies_path %>

app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AgencyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>